/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.hk.bfit.process;

import de.hk.bfit.io.GenericXmlHandler;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBException;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 *
 * @author palmherby
 */
public class TestCaseTest {

    public TestCaseTest() {
    }

    @BeforeClass
    public static void setUpClass() {
    }

    @Before
    public void setUp() {
    }


    @Test
    public void testSuccess() throws JAXBException {
        String xml = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" standalone=\"yes\"?>\n"
                + "<testCase>\n"
                + "    <description>jawoi</description>\n"
                + "    <initAction>\n"
                + "        <description>define your init commands here</description>\n"
                + "        <sqlCommands>insert into xyz ...</sqlCommands>\n"
                + "        <sqlCommands>update xyz where ...</sqlCommands>\n"
                + "    </initAction>\n"
                + "    <referenceAction>\n"
                + "        <description>jamei</description>\n"
                + "        <results>ein result</results>\n"
                + "        <select>select bla</select>\n"
                + "    </referenceAction>\n"
                + "    <referenceAction/>\n"
                + "    <resetAction>\n"
                + "        <description>define your reset commands here</description>\n"
                + "        <sqlCommands>delete from xyz where ...</sqlCommands>\n"
                + "        <sqlCommands>update xyz where ...</sqlCommands>\n"
                + "    </resetAction>\n"
                + "</testCase>";
        GenericXmlHandler genericXmlHandler = new GenericXmlHandler();
        System.out.println(xml);
        TestCase testCase2 = genericXmlHandler.unmarshall(TestCase.class, xml);

    }

    @Test
    public void testFailure() throws JAXBException {

        String xml = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" standalone=\"yes\"?>\n"
                + "<testCase>\n"
                + "    <description>Dies ist ein neuer TestCase</description>\n"
                + "    <initAction>\n"
                + "        <description>define your init commands here</description>\n"
                + "        <sqlCommands>insert into xyz ...</sqlCommands>\n"
                + "        <sqlCommands>update xyz where ...</sqlCommands>\n"
                + "    </initAction>\n"
                + "    <referenceActions>\n"
                + "        <description>Autogenerated Example</description>\n"
                + "        <results>1;</results>\n"
                //+ "        <results>2;</results>\n"
                + "        <select>select id from Person</select>\n"
                + "    </referenceActions>\n"
                + "    <resetAction>\n"
                + "        <description>define your reset commands here</description>\n"
                + "        <sqlCommands>delete from xyz where ...</sqlCommands>\n"
                + "        <sqlCommands>update xyz where ...</sqlCommands>\n"
                + "    </resetAction>\n"
                + "</testCase>";
        GenericXmlHandler genericXmlHandler = new GenericXmlHandler();
        System.out.println(xml);
        TestCase testCase2 = genericXmlHandler.unmarshall(TestCase.class, xml);
    }
}
