package de.hk.bfit.io;

import de.hk.bfit.model.ReferenceAction;
import de.hk.bfit.model.SelectCmd;
import de.hk.bfit.model.TestCase;
import de.hk.bfit.process.SqlProzessor;
import de.hk.bfit.process.enums.StubGeneration;
import org.apache.log4j.Logger;

import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import static de.hk.bfit.io.TestCaseHandler.writeTestcase;
import static de.hk.bfit.process.enums.StubGeneration.INITACTION;
import static de.hk.bfit.process.enums.StubGeneration.RESETACTION;
import static java.util.Arrays.asList;

public class TestCaseGenerator {

    private final Logger logger = Logger.getLogger(TestCaseGenerator.class);

    private  SqlProzessor sqlProzessor = null;

    public TestCaseGenerator(Connection connection) {
        sqlProzessor = new SqlProzessor(connection);
    }

    public TestCase generateTestCase(List<String> sqls) throws SQLException, IllegalArgumentException {
        return generateTestCase(sqls, null);
    }

    public void generateTestCase(String filename, List<String> sqls, StubGeneration... stubGeneration) throws IOException,SQLException{
        TestCase testCase = generateTestCase(sqls,stubGeneration);
        writeTestcase(testCase,filename);
    }

    public TestCase generateTestCase(List<String> sqls, StubGeneration... stubGeneration ) throws SQLException, IllegalArgumentException {
        logger.info("Generating TestCase");

        List<SelectCmd> selectCmd = new ArrayList<>();

        for (String sql : sqls) {
            logger.error("processing: " + sql);
            List<String> resultList = sqlProzessor.processCommand(sql);
            selectCmd.add(new SelectCmd("describe me!", sql, resultList));
        }
        TestCase testCase = new TestCase("This is a new testcase, generated by TestCaseProcessor.generate ...", new ReferenceAction("This is a new referenceAction ...", selectCmd));
        if (stubGeneration == null) {
            return testCase;
        }

        if (asList(stubGeneration).contains(INITACTION)) {
            testCase.getInitAction().getSqlCommands().add("insert ...");
            testCase.getInitAction().getSqlCommands().add("update ...");
            testCase.getInitAction().getSqlCommands().add("delete ...");
        }
        if (asList(stubGeneration).contains(RESETACTION)) {
            testCase.getResetAction().getSqlCommands().add("insert ...");
            testCase.getResetAction().getSqlCommands().add("update ...");
            testCase.getResetAction().getSqlCommands().add("delete ...");
        }
        return testCase;
    }
}
