package de.hk.bfit.io;

import de.hk.bfit.model.*;
import de.hk.bfit.process.SqlProzessor;
import de.hk.bfit.process.enums.StubGeneration;
import org.apache.log4j.Logger;

import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import static de.hk.bfit.io.TestCaseHandler.writeTestcase;
import static de.hk.bfit.process.enums.StubGeneration.INITACTION;
import static de.hk.bfit.process.enums.StubGeneration.RESETACTION;
import static java.util.Arrays.asList;

public class TestCaseGenerator {

    private final Logger logger = Logger.getLogger(TestCaseGenerator.class);

    private SqlProzessor sqlProzessor = null;

    public TestCaseGenerator(Connection connection) {
        sqlProzessor = new SqlProzessor(connection);
    }

    public TestCase generateTestCaseWithReferenceAfter(List<String> sqls) throws SQLException, IllegalArgumentException {
        return generateTestCaseWithReferenceAfter(sqls, null);
    }

    public void generateTestCaseWithReferenceAfter(String filename, List<String> sqls, StubGeneration... stubGeneration) throws IOException, SQLException {
        TestCase testCase = generateTestCaseWithReferenceAfter(sqls, stubGeneration);
        writeTestcase(testCase, filename);
    }

    public TestCase generateTestCaseWithReferenceAfter(List<String> sqlsReferenceAfter, StubGeneration... stubGeneration) throws SQLException, IllegalArgumentException {
        logger.info("Generating TestCase");

        List<SelectCmd> selectCmd = new ArrayList<>();

        for (String sql : sqlsReferenceAfter) {
            logger.info("processing: " + sql);
            List<String> resultList = sqlProzessor.processCommand(sql);
            selectCmd.add(new SelectCmd("describe me!", sql, resultList));
        }
        TestCase testCase = new TestCase("This is a new testcase, generated by TestCaseProcessor.generate ...", new ReferenceAction("This is a new referenceAction ...", selectCmd));
        if (stubGeneration == null) {
            return testCase;
        }

        if (asList(stubGeneration).contains(INITACTION)) {
            testCase.getInitAction().getSqlCommands().add("insert ...");
            testCase.getInitAction().getSqlCommands().add("update ...");
            testCase.getInitAction().getSqlCommands().add("delete ...");
        }
        if (asList(stubGeneration).contains(RESETACTION)) {
            testCase.getResetAction().getSqlCommands().add("insert ...");
            testCase.getResetAction().getSqlCommands().add("update ...");
            testCase.getResetAction().getSqlCommands().add("delete ...");
        }
        return testCase;
    }

    public TestCase generateTestCaseWithDefinedExecutionActions(String filename, List<DefinedExecutionAction> definedExecutionActions, List<DefinedReferenceAction> definedReferenceActions) throws IllegalArgumentException, IOException {
        TestCase newTestCase = new TestCase();
        newTestCase.setDescription(filename);
        newTestCase.setDefinedExecutionActions(definedExecutionActions);
        newTestCase.setDefinedReferenceActions(definedReferenceActions);
        TestCaseHandler.writeTestcase(newTestCase, filename);
        return newTestCase;
    }

}
